In [1]:
import tensorflow as tf
import numpy as np

In [2]:
def ex1(tensor: tf.Tensor) -> tf.Tensor:
    multiplied = tensor*tensor
    substracted = multiplied - tf.ones_like(multiplied)
    filtered = tf.where(substracted <= 2, substracted, tf.zeros_like(substracted))
    reshaped = tf.reshape(filtered, -1)
    return reshaped

In [3]:
t1 = tf.random.uniform(shape=[5], maxval=10)
t2 = tf.random.uniform(shape=[10,5], maxval=10)
t3 = tf.random.uniform(shape=[5,7,9], maxval=10)
print(ex1(t1))
print(ex1(t2))
print(ex1(t3))

tf.Tensor([-0.9202275 -0.9947807  0.         0.         0.       ], shape=(5,), dtype=float32)
tf.Tensor(
[-0.99875474  0.          0.          0.         -0.6802149   0.
  0.          1.307044    0.          0.          0.          0.
  0.          0.          0.          0.          0.         -0.3955202
 -0.98724425  0.          0.          0.         -0.95516485  0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.3355559
  0.         -0.2734893   0.          0.          0.          0.03533566
  0.          0.          0.          0.          0.          0.
  0.          0.        ], shape=(50,), dtype=float32)
tf.Tensor(
[ 0.         -0.8264349   0.          0.          0.          0.
  0.         -0.9920566   0.          0.          0.          0.
  0.          0.          0.         -0.94634223  0.         -0.9956507
  0.          0.          0.          0.         -0.07721484  0.9314389
  0.        

In [12]:
def ex2(tensor: tf.Tensor) -> tf.Tensor:
  assert (tf.shape(tensor).numpy() == [4, 3]).all(), "Wrong shape"
  reshaped = tf.reshape(tensor, [6,2])
  expanded = tf.expand_dims(reshaped, 0)
  tiled = tf.tile(expanded, tf.constant([5, 1, 1]))
  added = tiled + tf.random.uniform(shape=tiled.shape, maxval=10, dtype=tf.int32)
  clipped = tf.clip_by_value(added, 3, 5)
  return clipped


In [15]:
t4 = tf.constant(np.array([[1,2,3],[2,3,4],[4,5,6],[5,6,7]]), dtype=tf.int32)
print(ex2(t4))

tf.Tensor(
[[[5 5]
  [5 3]
  [4 5]
  [5 5]
  [5 5]
  [5 5]]

 [[4 3]
  [5 5]
  [5 5]
  [5 5]
  [5 5]
  [5 5]]

 [[5 5]
  [5 5]
  [5 5]
  [5 5]
  [5 5]
  [5 5]]

 [[3 5]
  [5 5]
  [3 5]
  [5 5]
  [5 5]
  [5 5]]

 [[5 4]
  [5 5]
  [5 5]
  [5 5]
  [5 5]
  [5 5]]], shape=(5, 6, 2), dtype=int32)


In [6]:
def ex3(tensor1: tf.Tensor, tensor2: tf.Tensor):
  assert (tf.shape(tensor1).numpy() == tf.shape(tensor2).numpy()).all(), "Wrong shape"
  twos = tf.where(tf.equal(tensor1, 2))
  corresponding = tf.gather_nd(tensor2, twos)
  mean = tf.math.reduce_mean(corresponding)
  multiplied = mean * tensor1
  concatenated = tf.concat([multiplied, tensor2], axis=0)
  reduced_max = tf.math.reduce_max(concatenated, axis=0)
  return reduced_max


In [7]:
t5 = tf.constant(np.array([[1, 2, 3], [4, 3, 2], [5, 2, 3]]), dtype=tf.int32)
t6 = tf.constant(np.array([[78, 43, 23], [45, 77, 32], [99, 88, 77]]), dtype=tf.int32)
print(ex3(t5, t6))

tf.Tensor([270 162 162], shape=(3,), dtype=int32)
